/**
 * Blog System API
 * An API for a blog system that allows users to create posts and comment on them.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    readonly id?: number;
    username?: string;
    email?: string;
}

